-- MySQL Script generated by MySQL Workbench
-- Sun Sep 11 18:55:26 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema optica
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema optica
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `optica` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`marca`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`marca` (
  `id_marca` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  PRIMARY KEY (`id_marca`))
ENGINE = InnoDB;

USE `optica` ;

-- -----------------------------------------------------
-- Table `optica`.`proveedores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `optica`.`proveedores` (
  `nombre` VARCHAR(200) NULL DEFAULT NULL,
  `direccion` VARCHAR(200) NULL DEFAULT NULL,
  `numero` INT NULL DEFAULT NULL,
  `piso` INT NULL DEFAULT NULL,
  `puerta` VARCHAR(4) NULL DEFAULT NULL,
  `ciudad` VARCHAR(100) NULL DEFAULT NULL,
  `codigo_postal` INT NULL DEFAULT NULL,
  `pais` VARCHAR(100) NULL DEFAULT NULL,
  `telefono` INT NULL DEFAULT NULL,
  `fax` INT NULL DEFAULT NULL,
  `NIF` VARCHAR(10) NOT NULL,
  `marca_id_marca` INT NOT NULL,
  PRIMARY KEY (`NIF`, `marca_id_marca`),
  INDEX `fk_proveedores_marca1_idx` (`marca_id_marca` ASC) VISIBLE,
  CONSTRAINT `fk_proveedores_marca1`
    FOREIGN KEY (`marca_id_marca`)
    REFERENCES `mydb`.`marca` (`id_marca`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `optica`.`gafas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `optica`.`gafas` (
  `marca` INT NULL DEFAULT NULL,
  `graduacion` FLOAT NULL DEFAULT NULL,
  `tipo_montura` VARCHAR(15) NULL DEFAULT NULL,
  `color_montura` VARCHAR(20) NULL DEFAULT NULL,
  `color_vidrio` VARCHAR(20) NULL DEFAULT NULL,
  `precio` FLOAT NULL DEFAULT NULL,
  `proveedores_NIF` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`proveedores_NIF`),
  INDEX `fk_gafas_proveedores_idx` (`proveedores_NIF` ASC) VISIBLE,
  CONSTRAINT `fk_gafas_proveedores`
    FOREIGN KEY (`proveedores_NIF`)
    REFERENCES `optica`.`proveedores` (`NIF`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `optica`.`clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `optica`.`clientes` (
  `nombre` VARCHAR(200) NULL DEFAULT NULL,
  `direccion` VARCHAR(200) NULL DEFAULT NULL,
  `numero` INT NULL DEFAULT NULL,
  `piso` INT NULL DEFAULT NULL,
  `puerta` VARCHAR(4) NULL DEFAULT NULL,
  `ciudad` VARCHAR(100) NULL DEFAULT NULL,
  `codigo_postal` INT NULL DEFAULT NULL,
  `pais` VARCHAR(100) NULL DEFAULT NULL,
  `telefono` INT NULL DEFAULT NULL,
  `email` VARCHAR(200) NULL DEFAULT NULL,
  `fecha_registro` DATE NULL DEFAULT NULL,
  `recomendado_por` VARCHAR(200) NULL DEFAULT NULL,
  `vendedor` VARCHAR(200) NULL DEFAULT NULL,
  `gafas_proveedores_NIF` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`gafas_proveedores_NIF`),
  CONSTRAINT `fk_clientes_gafas1`
    FOREIGN KEY (`gafas_proveedores_NIF`)
    REFERENCES `optica`.`gafas` (`proveedores_NIF`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
