-- MySQL Script generated by MySQL Workbench
-- Sun Sep 11 18:43:48 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema pizzeria
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema pizzeria
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `pizzeria` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `pizzeria`.`producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzeria`.`producto` (
  `id_producto` INT NOT NULL,
  `nombre` VARCHAR(30) NULL DEFAULT NULL,
  `descripcion` VARCHAR(250) NULL DEFAULT NULL,
  `imagen` INT NULL DEFAULT NULL,
  `precio` FLOAT NULL DEFAULT NULL,
  PRIMARY KEY (`id_producto`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `mydb`.`pizza`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`pizza` (
  `idpizza` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `producto_id_producto` INT NOT NULL,
  PRIMARY KEY (`idpizza`, `producto_id_producto`),
  INDEX `fk_pizza_producto_idx` (`producto_id_producto` ASC) VISIBLE,
  CONSTRAINT `fk_pizza_producto`
    FOREIGN KEY (`producto_id_producto`)
    REFERENCES `pizzeria`.`producto` (`id_producto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`hamburguesa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`hamburguesa` (
  `id_hamburguesa` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `producto_id_producto` INT NOT NULL,
  PRIMARY KEY (`id_hamburguesa`, `producto_id_producto`),
  INDEX `fk_hamburguesa_producto1_idx` (`producto_id_producto` ASC) VISIBLE,
  CONSTRAINT `fk_hamburguesa_producto1`
    FOREIGN KEY (`producto_id_producto`)
    REFERENCES `pizzeria`.`producto` (`id_producto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`bebida`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`bebida` (
  `id_bebida` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `producto_id_producto` INT NOT NULL,
  PRIMARY KEY (`id_bebida`, `producto_id_producto`),
  INDEX `fk_bebida_producto1_idx` (`producto_id_producto` ASC) VISIBLE,
  CONSTRAINT `fk_bebida_producto1`
    FOREIGN KEY (`producto_id_producto`)
    REFERENCES `pizzeria`.`producto` (`id_producto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `pizzeria` ;

-- -----------------------------------------------------
-- Table `pizzeria`.`categoria_pizza`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzeria`.`categoria_pizza` (
  `id_pizza` INT NOT NULL,
  `nombre` VARCHAR(50) NULL DEFAULT NULL,
  `pizza_idpizza` INT NOT NULL,
  PRIMARY KEY (`id_pizza`, `pizza_idpizza`),
  INDEX `fk_categoria_pizza_pizza1_idx` (`pizza_idpizza` ASC) VISIBLE,
  CONSTRAINT `fk_categoria_pizza_pizza1`
    FOREIGN KEY (`pizza_idpizza`)
    REFERENCES `mydb`.`pizza` (`idpizza`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `pizzeria`.`reparto_domicilio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzeria`.`reparto_domicilio` (
  `id_pedido` INT NOT NULL,
  `id_repartidor` INT NULL DEFAULT NULL,
  `hora_reparto` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id_pedido`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `pizzeria`.`empleado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzeria`.`empleado` (
  `id_empleado` INT NOT NULL,
  `nombre` VARCHAR(100) NULL DEFAULT NULL,
  `apellidos` VARCHAR(100) NULL DEFAULT NULL,
  `nif` VARCHAR(10) NULL DEFAULT NULL,
  `telefono` INT NULL DEFAULT NULL,
  `cocina_o_domicilio` VARCHAR(100) NULL DEFAULT NULL,
  `reparto_domicilio_id_pedido` INT NOT NULL,
  PRIMARY KEY (`id_empleado`, `reparto_domicilio_id_pedido`),
  INDEX `fk_empleado_reparto_domicilio1_idx` (`reparto_domicilio_id_pedido` ASC) VISIBLE,
  CONSTRAINT `fk_empleado_reparto_domicilio1`
    FOREIGN KEY (`reparto_domicilio_id_pedido`)
    REFERENCES `pizzeria`.`reparto_domicilio` (`id_pedido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `pizzeria`.`localidad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzeria`.`localidad` (
  `id_localidad` INT NOT NULL,
  `nombre` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`id_localidad`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `pizzeria`.`provincia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzeria`.`provincia` (
  `id_provincia` INT NOT NULL,
  `nombre` VARCHAR(100) NULL DEFAULT NULL,
  `localidad_id_localidad` INT NOT NULL,
  PRIMARY KEY (`id_provincia`, `localidad_id_localidad`),
  INDEX `fk_provincia_localidad1_idx` (`localidad_id_localidad` ASC) VISIBLE,
  CONSTRAINT `fk_provincia_localidad1`
    FOREIGN KEY (`localidad_id_localidad`)
    REFERENCES `pizzeria`.`localidad` (`id_localidad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `pizzeria`.`tienda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzeria`.`tienda` (
  `id_tienda` INT NOT NULL,
  `direccion` VARCHAR(100) NULL DEFAULT NULL,
  `codigo_postal` INT NULL DEFAULT NULL,
  `localidad` VARCHAR(100) NULL DEFAULT NULL,
  `provincia` INT NULL DEFAULT NULL,
  `pedido_id_pedido` INT NOT NULL,
  `pedido_tienda_id_tienda` INT NOT NULL,
  `empleado_id_empleado` INT NOT NULL,
  `empleado_reparto_domicilio_id_pedido` INT NOT NULL,
  PRIMARY KEY (`id_tienda`, `pedido_id_pedido`, `pedido_tienda_id_tienda`, `empleado_id_empleado`, `empleado_reparto_domicilio_id_pedido`),
  INDEX `fk_tienda_pedido1_idx` (`pedido_id_pedido` ASC, `pedido_tienda_id_tienda` ASC) VISIBLE,
  INDEX `fk_tienda_empleado1_idx` (`empleado_id_empleado` ASC, `empleado_reparto_domicilio_id_pedido` ASC) VISIBLE,
  INDEX `fk_privincia_idx` (`provincia` ASC) VISIBLE,
  CONSTRAINT `fk_tienda_pedido1`
    FOREIGN KEY (`pedido_id_pedido` , `pedido_tienda_id_tienda`)
    REFERENCES `pizzeria`.`pedido` (`id_pedido` , `tienda_id_tienda`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tienda_empleado1`
    FOREIGN KEY (`empleado_id_empleado` , `empleado_reparto_domicilio_id_pedido`)
    REFERENCES `pizzeria`.`empleado` (`id_empleado` , `reparto_domicilio_id_pedido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_privincia`
    FOREIGN KEY (`provincia`)
    REFERENCES `pizzeria`.`provincia` (`id_provincia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `pizzeria`.`pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzeria`.`pedido` (
  `id_pedido` INT NOT NULL,
  `hora` TIMESTAMP NULL DEFAULT NULL,
  `domicilio_recogida` VARCHAR(10) NULL DEFAULT NULL,
  `productos` INT NULL DEFAULT NULL,
  `precio_total` FLOAT NULL DEFAULT NULL,
  `producto_id_producto` INT NOT NULL,
  `tienda_id_tienda` INT NOT NULL,
  `clientes_id_cliente` INT NOT NULL,
  `reparto_domicilio_id_pedido` INT NOT NULL,
  PRIMARY KEY (`id_pedido`, `tienda_id_tienda`, `clientes_id_cliente`, `reparto_domicilio_id_pedido`),
  INDEX `fk_pedido_producto1_idx` (`producto_id_producto` ASC) VISIBLE,
  INDEX `fk_pedido_tienda1_idx` (`tienda_id_tienda` ASC) VISIBLE,
  INDEX `fk_pedido_clientes1_idx` (`clientes_id_cliente` ASC) VISIBLE,
  INDEX `fk_pedido_reparto_domicilio1_idx` (`reparto_domicilio_id_pedido` ASC) VISIBLE,
  CONSTRAINT `fk_pedido_producto1`
    FOREIGN KEY (`producto_id_producto`)
    REFERENCES `pizzeria`.`producto` (`id_producto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pedido_tienda1`
    FOREIGN KEY (`tienda_id_tienda`)
    REFERENCES `pizzeria`.`tienda` (`id_tienda`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pedido_clientes1`
    FOREIGN KEY (`clientes_id_cliente`)
    REFERENCES `pizzeria`.`clientes` (`id_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pedido_reparto_domicilio1`
    FOREIGN KEY (`reparto_domicilio_id_pedido`)
    REFERENCES `pizzeria`.`reparto_domicilio` (`id_pedido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `pizzeria`.`clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzeria`.`clientes` (
  `id_cliente` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(200) NULL DEFAULT NULL,
  `apellidos` VARCHAR(200) NULL DEFAULT NULL,
  `dni` VARCHAR(10) NULL DEFAULT NULL,
  `direccion` VARCHAR(200) NULL DEFAULT NULL,
  `numero` INT NULL DEFAULT NULL,
  `piso` INT NULL DEFAULT NULL,
  `puerta` VARCHAR(4) NULL DEFAULT NULL,
  `codigo_postal` INT NULL DEFAULT NULL,
  `localidad` VARCHAR(100) NULL DEFAULT NULL,
  `provincia` INT NULL DEFAULT NULL,
  `telefono` INT NULL DEFAULT NULL,
  `pedido_id_pedido` INT NOT NULL,
  PRIMARY KEY (`id_cliente`),
  INDEX `fk_clientes_pedido1_idx` (`pedido_id_pedido` ASC) VISIBLE,
  INDEX `fk_provincia_idx` (`provincia` ASC) VISIBLE,
  CONSTRAINT `fk_clientes_pedido1`
    FOREIGN KEY (`pedido_id_pedido`)
    REFERENCES `pizzeria`.`pedido` (`id_pedido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_provincia`
    FOREIGN KEY (`provincia`)
    REFERENCES `pizzeria`.`provincia` (`id_provincia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
